CREATE TABLE 'AspNetUsers' (
 Id varchar (128) NOT NULL,
 Email varchar (256) DEFAULT NULL,
 EmailConfirmed tinyint (1) NOT NULL,
 PasswordHash longtext,
 SecurityStamp longtext,
 PhoneNumber longtext,
 PhoneNumberConfirmed tinyint (1) NOT NULL,
 TwoFactorEnabled tinyint (1) NOT NULL,
 LockoutEndDateUtc datetime DEFAULT NULL,
 LockoutEnabled tinyint (1) NOT NULL,
 LockoutEnd varchar(100),
 AccessFailedCount int (11) NOT NULL,
 UserName varchar (256) NOT NULL,
 IsActivated tinyint(1) NOT NULL DEFAULT (0),
 ConcurrencyStamp nvarchar(1000),
 NormalizedEmail varchar(1000),
 NormalizedUserName varchar(1000),
 Token varchar(500),
 FirstName varchar(50),
 LastName varchar(50),
 UpdateDate varchar(50),
 UpdateUser varchar(256),
 PRIMARY KEY (Id));

